### ISSUE TITLE
Cannot find type '_opaque_Hashable' in scope

### ISSUE THREAD

**Issue by SagarUnagar** [vmanot/Reduce#5]
Starting new project.

SwiftUI
Minimum Deployment - iOS 14
Xcode 14.2

Added Reactor as dependency. It wont be able to build. Giving me error on `Reactor/Sources/Intramodular/Dispatch/ReactorDispatchItem.swift`

![reactor-error](https://user-images.githubusercontent.com/16893693/220545004-4ae87ac8-edde-45e4-b6f1-e040bad874b6.png)

**Comment by vmanot** [comment]
@SagarUnagar thanks for reporting, this should be fixed now.
